### ISSUE TITLE
When will the Successors be ready?

### ISSUE THREAD

**Issue by TheGiraffe3** [Daeridanii1/successors#13]
Will the Successors be ready by 0.10.9? They look like they would be really fun to have in the game.

**Comment by Daeridanii1** [comment]
There's going to be two stages of readiness.
The nearest one to now will be an initial PR, where I convert all the files here to a PR format and pull request the Endless Sky repository. I hope to do that **very soon** TM---the last big chunk of material I want in that initial PR is the reworked intro missions, which I'm currently making my way through.
Once it's PRed, though, the timeline is largely out of my hands. Big PRs take a long time to review; there's a lot of writing and art here for reviewers to check over and comment on. So I'm not sure in which version number the Successors might officially make their way into the game; all I can say is that I will strive to integrate review comments in a timely manner.

**Comment by TheGiraffe3** [comment]
0.10.9 isn't due until September 28, so three months. That should be enough.

**Comment by TheGiraffe3** [comment]
@Daeridanii1 there doesn't seem to be a launcher for the kinetic lance or the hv spike. I assume that isn't intentional?

**Comment by Daeridanii1** [comment]
The "Sjeja" Kinetic Lance is the launcher; the High-Velocity Spike is the ammunition for it.
